# Generated by Django 2.2.3 on 2019-07-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Recipe',
        ),
    ]
